<!DOCTYPE html>
<html lang="uk">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Сторінку не знайдено</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <section style="text-align:center; padding: 100px;">
    <h1>404</h1>
    <p>Ой! Сторінку не знайдено.</p>
    <a href="index.html">Повернутись на головну</a>
  </section>
</body>
</html>
